In [1]:
import torch
torch.__version__

'2.4.1'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([1,4])
vector

tensor([1, 4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
tensor = torch.tensor([[[1,2,3],[3,6,8],[3,3,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 8],
         [3, 3, 5]]])

In [12]:
tensor.shape, tensor.ndim

(torch.Size([1, 3, 3]), 3)

In [13]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.5097, 0.1180, 0.5313, 0.4599],
         [0.9719, 0.7370, 0.2343, 0.0554],
         [0.2380, 0.5387, 0.9043, 0.5973]]),
 torch.float32)

In [14]:
rand_image = torch.rand(size=(256,256,3))
rand_image.shape, rand_image.ndim

(torch.Size([256, 256, 3]), 3)

In [15]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [16]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [17]:
zero_to_ten = torch.arange(0, 10,2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [18]:
torch_zeros = torch.zeros_like(zero_to_ten)
torch_zeros

tensor([0, 0, 0, 0, 0])

In [19]:
float_tensor  = torch.tensor(
    [1,3,4,5],
    dtype=torch.float32,
    device='cpu',
    requires_grad=False
)
float_tensor.shape, float_tensor.dtype, float_tensor.device

(torch.Size([4]), torch.float32, device(type='cpu'))

In [20]:
float16_tensor = torch.tensor([1,2,3], dtype=torch.float16)
float16_tensor.dtype

torch.float16

In [21]:
some_tensor = torch.rand(3,5)

print(some_tensor)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

tensor([[0.8616, 0.3174, 0.8770, 0.7268, 0.6816],
        [0.3900, 0.4377, 0.9906, 0.2610, 0.1679],
        [0.2061, 0.9905, 0.1698, 0.2995, 0.8368]])
torch.Size([3, 5])
torch.float32
cpu


In [22]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [23]:
tensor * 10

tensor([10, 20, 30])

In [24]:
tensor

tensor([1, 2, 3])

In [25]:
tensor -= 5
tensor

tensor([-4, -3, -2])

In [26]:
tensor += 2
tensor

tensor([-2, -1,  0])

In [27]:
torch.multiply(tensor, 10)

tensor([-20, -10,   0])

In [28]:
tensor

tensor([-2, -1,  0])

In [29]:
tensor * tensor

tensor([4, 1, 0])

In [30]:
tensor

tensor([-2, -1,  0])

In [31]:
torch.matmul(tensor, tensor)

tensor(5)

In [32]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 854 μs, sys: 588 μs, total: 1.44 ms
Wall time: 927 μs


tensor(5)

In [33]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 28 μs, sys: 0 ns, total: 28 μs
Wall time: 34.1 μs


tensor(5)

In [34]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
try:
  print(torch.matmul(tensor_A, tensor_B)) # (this will error)
except Exception as e:
    print(e)

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [35]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [36]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [37]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [38]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [40]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [41]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [42]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [43]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [44]:
tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [45]:
tensor = tensor.unsqueeze(dim=0)
tensor

tensor([[10., 20., 30., 40., 50., 60., 70., 80., 90.]])

In [46]:
tensor = tensor.unsqueeze(dim=1)
tensor

tensor([[[10., 20., 30., 40., 50., 60., 70., 80., 90.]]])

In [47]:
tensor.shape

torch.Size([1, 1, 9])

In [48]:
tensor = tensor.squeeze()
tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [49]:
n_tensor = torch.stack([tensor, tensor, tensor],dim=1)
n_tensor

tensor([[10., 10., 10.],
        [20., 20., 20.],
        [30., 30., 30.],
        [40., 40., 40.],
        [50., 50., 50.],
        [60., 60., 60.],
        [70., 70., 70.],
        [80., 80., 80.],
        [90., 90., 90.]])

In [50]:
n_rand = torch.rand(size=(3,224,224))
n_rand.shape, n_rand.permute(2,0,1).shape

(torch.Size([3, 224, 224]), torch.Size([224, 3, 224]))

In [51]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [52]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [53]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [54]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [55]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [56]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [57]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [58]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [59]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [60]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [61]:
rand_a = torch.rand(size=(3,4))
rand_b = torch.rand(size=(3,4))
print(f"Tensor A:\n{rand_a}\n")
print(f"Tensor B:\n{rand_b}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
rand_a == rand_b

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [65]:
torch.manual_seed(seed=42)
rand_c = torch.rand(size=(3,4))

torch.manual_seed(seed=42)
rand_d = torch.rand(size=(3,4))
print(f"Tensor C:\n{rand_c}\n")
print(f"Tensor D:\n{rand_d}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
rand_c == rand_d

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [66]:
!nvidia-smi

Mon Sep 16 13:08:42 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   59C    P0   248W / 300W |  32497MiB / 32768MiB |     99%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:07:00.0 Off |                    0 |
| N/A   

In [67]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [68]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [69]:
# Count number of devices
torch.cuda.device_count()

8

In [70]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

False

In [72]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available
device

'cuda'

In [73]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [75]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [76]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')